// <auto-generated />
using System;
using ERP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.API.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    partial class ERPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.API.Models.ApplicationRoleGroup", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "GroupId");

                    b.ToTable("ApplicationRoleGroups");
                });

            modelBuilder.Entity("ERP.API.Models.ApplicationUserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("ApplicationUserGroups");
                });

            modelBuilder.Entity("ERP.API.Models.AspNetRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RMenuGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("RMenuGroupOrder")
                        .HasColumnType("int");

                    b.Property<string>("RMenuIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMenuType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ERP.API.Models.CompanyMaster", b =>
                {
                    b.Property<int>("CMPYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CMPYID"));

                    b.Property<string>("CMPYADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYADDR3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYCITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYCONTACTPERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYEMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYGSTNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYPANNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYPHONE1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYPHONE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYPINCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMPYSTATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSRID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("DISPSTATUS")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PRCSDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("CMPYID");

                    b.ToTable("COMPANYMASTER");
                });

            modelBuilder.Entity("ERP.API.Models.CustomerLocationDetail", b =>
                {
                    b.Property<int>("CATEAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CATEAID"));

                    b.Property<string>("CATEAADDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEAADDR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEAADDR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEA_CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEA_COUNTRY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEA_GST_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEA_PINCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CATEID")
                        .HasColumnType("int");

                    b.Property<int>("LOCTID")
                        .HasColumnType("int");

                    b.Property<int>("STATEID")
                        .HasColumnType("int");

                    b.HasKey("CATEAID");

                    b.ToTable("CUSTOMERLOCATIONDETAIL");
                });

            modelBuilder.Entity("ERP.API.Models.CustomerMaster", b =>
                {
                    b.Property<int>("CATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CATEID"));

                    b.Property<int>("ACHEADID")
                        .HasColumnType("int");

                    b.Property<string>("CATEBANKADDR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANKBRNCHNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANKNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANK_ACNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANK_ACTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANK_IBAN_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANK_IFCS_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEBANK_SWIFT_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATECODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEDNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATENAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CATENO")
                        .HasColumnType("int");

                    b.Property<int>("CATETID")
                        .HasColumnType("int");

                    b.Property<string>("CATE_GST_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATE_PAN_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATE_TALLY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATE_TAN_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CURNID")
                        .HasColumnType("int");

                    b.Property<string>("CUSRID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DISPSTATUS")
                        .HasColumnType("smallint");

                    b.Property<int?>("LMUSRID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PRCSDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("CATEID");

                    b.ToTable("CUSTOMERMASTER");
                });

            modelBuilder.Entity("ERP.API.Models.EmailOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailOtps");
                });

            modelBuilder.Entity("ERP.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ERP.API.Models.LocationMaster", b =>
                {
                    b.Property<int>("LOCTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LOCTID"));

                    b.Property<int>("DISPSTATUS")
                        .HasColumnType("int");

                    b.Property<string>("LOCTNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("STATEID")
                        .HasColumnType("int");

                    b.HasKey("LOCTID");

                    b.ToTable("LOCATIONMASTER");
                });

            modelBuilder.Entity("ERP.API.Models.StateMaster", b =>
                {
                    b.Property<int>("STATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STATEID"));

                    b.Property<int>("DISPSTATUS")
                        .HasColumnType("int");

                    b.Property<string>("STATENAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("STATEID");

                    b.ToTable("STATEMASTER");
                });

            modelBuilder.Entity("ERP.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
